---
env:
- CGO_ENABLED=0

before:
  hooks:
  - go mod download

build:
  main: main.go
  binary: taketo-{{ .Os }}-{{ .Arch }}
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7

archives:
- format: binary

checksum:
  name_template: checksums.txt
